-- MySQL Script generated by MySQL Workbench
-- Mon Sep 15 17:56:46 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_tuso
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_tuso
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_tuso` DEFAULT CHARACTER SET utf8mb3 ;
USE `db_tuso` ;

-- -----------------------------------------------------
-- Table `db_tuso`.`tipo_calificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tuso`.`tipo_calificacion` (
  `id_tipo_calificacion` INT NOT NULL,
  `Tipo_cal` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipo_calificacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_tuso`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tuso`.`roles` (
  `id_roles` INT NOT NULL,
  `Nombre` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_roles`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_tuso`.`tipo_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tuso`.`tipo_documento` (
  `id_tipo_id` INT NOT NULL,
  `Nombre` VARCHAR(40) NOT NULL,
  `Numero_doc` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_tipo_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_tuso`.`ubicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tuso`.`ubicacion` (
  `id_ubicacion` INT NOT NULL,
  `Pais` VARCHAR(20) NOT NULL,
  `Departamento` VARCHAR(20) NOT NULL,
  `Ciudad` VARCHAR(20) NOT NULL,
  `Direccion` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_ubicacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_tuso`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tuso`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `Nombre1` VARCHAR(20) NOT NULL,
  `Nombre2` VARCHAR(20) NOT NULL,
  `Apellido1` VARCHAR(20) NOT NULL,
  `Apellido2` VARCHAR(20) NOT NULL,
  `Correo_electronico` VARCHAR(60) NOT NULL,
  `Telefono` VARCHAR(10) NOT NULL,
  `Fecha_nac` DATE NOT NULL,
  `Sexo` VARCHAR(20) NOT NULL,
  `Ocupacion` VARCHAR(30) NOT NULL,
  `Puntos_xp` FLOAT NOT NULL,
  `Roles_id_roles` INT NOT NULL,
  `Ubicacion_id_ubicacion` INT NOT NULL,
  `Tipo_documento_id_tipo_id` INT NOT NULL,
  PRIMARY KEY (`id_usuario`, `Roles_id_roles`, `Ubicacion_id_ubicacion`, `Tipo_documento_id_tipo_id`),
  INDEX `fk_Usuarios_Roles1_idx` (`Roles_id_roles` ASC) VISIBLE,
  INDEX `fk_Usuarios_Ubicacion1_idx` (`Ubicacion_id_ubicacion` ASC) VISIBLE,
  INDEX `fk_Usuarios_Tipo_documento1_idx` (`Tipo_documento_id_tipo_id` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_Roles1`
    FOREIGN KEY (`Roles_id_roles`)
    REFERENCES `db_tuso`.`roles` (`id_roles`),
  CONSTRAINT `fk_Usuarios_Tipo_documento1`
    FOREIGN KEY (`Tipo_documento_id_tipo_id`)
    REFERENCES `db_tuso`.`tipo_documento` (`id_tipo_id`),
  CONSTRAINT `fk_Usuarios_Ubicacion1`
    FOREIGN KEY (`Ubicacion_id_ubicacion`)
    REFERENCES `db_tuso`.`ubicacion` (`id_ubicacion`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_tuso`.`codigos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tuso`.`codigos` (
  `id_codigo` INT NOT NULL,
  `Nombre` VARCHAR(20) NOT NULL,
  `Valor` FLOAT NOT NULL,
  `Usuarios_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_codigo`, `Usuarios_id_usuario`),
  INDEX `fk_Codigos_Usuarios1_idx` (`Usuarios_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Codigos_Usuarios1`
    FOREIGN KEY (`Usuarios_id_usuario`)
    REFERENCES `db_tuso`.`usuarios` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_tuso`.`tipo_turismo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tuso`.`tipo_turismo` (
  `id_tipo_turismo` INT NOT NULL,
  `Tipo_de_turismo` VARCHAR(100) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_turismo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_tuso`.`viajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tuso`.`viajes` (
  `id_viajes` INT NOT NULL,
  `Num_personas` INT NOT NULL,
  `Presupuesto` FLOAT NOT NULL,
  `Preferencias_distancia` FLOAT NOT NULL,
  `Usuarios_id_usuario` INT NOT NULL,
  `Codigos_id_codigo` INT NOT NULL,
  `Ubicacion_id_ubicacion` INT NOT NULL,
  `Tipo_turismo_id_tipo_turismo` INT NOT NULL,
  PRIMARY KEY (`id_viajes`, `Usuarios_id_usuario`, `Codigos_id_codigo`, `Ubicacion_id_ubicacion`, `Tipo_turismo_id_tipo_turismo`),
  INDEX `fk_Viajes_Usuarios_idx` (`Usuarios_id_usuario` ASC) VISIBLE,
  INDEX `fk_Viajes_Codigos1_idx` (`Codigos_id_codigo` ASC) VISIBLE,
  INDEX `fk_Viajes_Ubicacion1_idx` (`Ubicacion_id_ubicacion` ASC) VISIBLE,
  INDEX `fk_Viajes_Tipo_turismo1_idx` (`Tipo_turismo_id_tipo_turismo` ASC) VISIBLE,
  CONSTRAINT `fk_Viajes_Codigos`
    FOREIGN KEY (`Codigos_id_codigo`)
    REFERENCES `db_tuso`.`codigos` (`id_codigo`),
  CONSTRAINT `fk_Viajes_Codigos1`
    FOREIGN KEY (`Codigos_id_codigo`)
    REFERENCES `db_tuso`.`codigos` (`id_codigo`),
  CONSTRAINT `fk_Viajes_Tipo_turismo1`
    FOREIGN KEY (`Tipo_turismo_id_tipo_turismo`)
    REFERENCES `db_tuso`.`tipo_turismo` (`id_tipo_turismo`),
  CONSTRAINT `fk_Viajes_TipoTurismo`
    FOREIGN KEY (`Tipo_turismo_id_tipo_turismo`)
    REFERENCES `db_tuso`.`tipo_turismo` (`id_tipo_turismo`),
  CONSTRAINT `fk_Viajes_Ubicacion`
    FOREIGN KEY (`Ubicacion_id_ubicacion`)
    REFERENCES `db_tuso`.`ubicacion` (`id_ubicacion`),
  CONSTRAINT `fk_Viajes_Ubicacion1`
    FOREIGN KEY (`Ubicacion_id_ubicacion`)
    REFERENCES `db_tuso`.`ubicacion` (`id_ubicacion`),
  CONSTRAINT `fk_Viajes_Usuarios`
    FOREIGN KEY (`Usuarios_id_usuario`)
    REFERENCES `db_tuso`.`usuarios` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_tuso`.`calificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tuso`.`calificacion` (
  `id_calificacion` INT NOT NULL,
  `Puntuacion` FLOAT NOT NULL,
  `Reseña` VARCHAR(1000) NOT NULL,
  `Viajes_id_viajes` INT NOT NULL,
  `Tipo_calificacion_id_tipo_calificacion` INT NOT NULL,
  PRIMARY KEY (`id_calificacion`, `Viajes_id_viajes`, `Tipo_calificacion_id_tipo_calificacion`),
  INDEX `fk_Calificacion_Viajes1_idx` (`Viajes_id_viajes` ASC) VISIBLE,
  INDEX `fk_Calificacion_Tipo_calificacion1_idx` (`Tipo_calificacion_id_tipo_calificacion` ASC) VISIBLE,
  CONSTRAINT `fk_Calificacion_Tipo_calificacion1`
    FOREIGN KEY (`Tipo_calificacion_id_tipo_calificacion`)
    REFERENCES `db_tuso`.`tipo_calificacion` (`id_tipo_calificacion`),
  CONSTRAINT `fk_Calificacion_Viajes1`
    FOREIGN KEY (`Viajes_id_viajes`)
    REFERENCES `db_tuso`.`viajes` (`id_viajes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_tuso`.`caracteristicas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tuso`.`caracteristicas` (
  `id_caracteristica` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_caracteristica`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_tuso`.`chats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tuso`.`chats` (
  `id_chat` INT NOT NULL,
  `Viajes_id_viajes` INT NOT NULL,
  PRIMARY KEY (`id_chat`, `Viajes_id_viajes`),
  INDEX `fk_Chats_Viajes1_idx` (`Viajes_id_viajes` ASC) VISIBLE,
  CONSTRAINT `fk_Chats_Viajes1`
    FOREIGN KEY (`Viajes_id_viajes`)
    REFERENCES `db_tuso`.`viajes` (`id_viajes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_tuso`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tuso`.`comentarios` (
  `id_comentario` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  `Chats_id_chat` INT NOT NULL,
  PRIMARY KEY (`id_comentario`, `Chats_id_chat`),
  INDEX `fk_Comentario_Chats1_idx` (`Chats_id_chat` ASC) VISIBLE,
  CONSTRAINT `fk_Comentario_Chats1`
    FOREIGN KEY (`Chats_id_chat`)
    REFERENCES `db_tuso`.`chats` (`id_chat`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_tuso`.`destinos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tuso`.`destinos` (
  `id_destinos` INT NOT NULL,
  `Nombre_destino` VARCHAR(40) NOT NULL,
  `Usuarios_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_destinos`, `Usuarios_id_usuario`),
  INDEX `fk_Destinos_Usuarios1_idx` (`Usuarios_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Destinos_Usuarios`
    FOREIGN KEY (`Usuarios_id_usuario`)
    REFERENCES `db_tuso`.`usuarios` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_tuso`.`feed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tuso`.`feed` (
  `id_feed` INT NOT NULL,
  `Descripcion` VARCHAR(100) NOT NULL,
  `Likes` INT NOT NULL,
  `Fecha_publi` DATE NOT NULL,
  `Usuarios_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_feed`, `Usuarios_id_usuario`),
  INDEX `fk_Feed_Usuarios1_idx` (`Usuarios_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Feed_Usuarios`
    FOREIGN KEY (`Usuarios_id_usuario`)
    REFERENCES `db_tuso`.`usuarios` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_tuso`.`gustos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tuso`.`gustos` (
  `id_gustos` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(60) NOT NULL,
  `Estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_gustos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_tuso`.`invitaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tuso`.`invitaciones` (
  `id_invitacion` INT NOT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  `Rol` VARCHAR(20) NOT NULL,
  `Viajes_id_viajes` INT NOT NULL,
  PRIMARY KEY (`id_invitacion`, `Viajes_id_viajes`),
  INDEX `fk_Invitacion_Viajes1_idx` (`Viajes_id_viajes` ASC) VISIBLE,
  CONSTRAINT `fk_Invitacion_Viajes1`
    FOREIGN KEY (`Viajes_id_viajes`)
    REFERENCES `db_tuso`.`viajes` (`id_viajes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_tuso`.`invi_viaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tuso`.`invi_viaje` (
  `Usuarios_id_usuario` INT NOT NULL,
  `Invitacion_id_invitacion` INT NOT NULL,
  PRIMARY KEY (`Usuarios_id_usuario`, `Invitacion_id_invitacion`),
  INDEX `fk_Usuarios_has_Invitacion_Invitacion1_idx` (`Invitacion_id_invitacion` ASC) VISIBLE,
  INDEX `fk_Usuarios_has_Invitacion_Usuarios1_idx` (`Usuarios_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_InviViaje_Invitacion`
    FOREIGN KEY (`Invitacion_id_invitacion`)
    REFERENCES `db_tuso`.`invitaciones` (`id_invitacion`),
  CONSTRAINT `fk_InviViaje_Usuarios`
    FOREIGN KEY (`Usuarios_id_usuario`)
    REFERENCES `db_tuso`.`usuarios` (`id_usuario`),
  CONSTRAINT `fk_Usuarios_has_Invitacion_Invitacion1`
    FOREIGN KEY (`Invitacion_id_invitacion`)
    REFERENCES `db_tuso`.`invitaciones` (`id_invitacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_tuso`.`lugares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tuso`.`lugares` (
  `id_lugares` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Lat` FLOAT NOT NULL,
  `Longitud` FLOAT NULL DEFAULT NULL,
  `Horarios` VARCHAR(45) NOT NULL,
  `Precio` FLOAT NOT NULL,
  `Destinos_id_destinos` INT NOT NULL,
  PRIMARY KEY (`id_lugares`, `Destinos_id_destinos`),
  INDEX `fk_Lugares_Destinos1_idx` (`Destinos_id_destinos` ASC) VISIBLE,
  CONSTRAINT `fk_Lugares_Destinos1`
    FOREIGN KEY (`Destinos_id_destinos`)
    REFERENCES `db_tuso`.`destinos` (`id_destinos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_tuso`.`lug_car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tuso`.`lug_car` (
  `id_lug_car` INT NOT NULL,
  `Lugares_id_lugares` INT NOT NULL,
  `Caracteristicas_id_caracteristica` INT NOT NULL,
  `Descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_lug_car`, `Lugares_id_lugares`, `Caracteristicas_id_caracteristica`),
  INDEX `fk_Lugares_has_Caracteristicas_Caracteristicas1_idx` (`Caracteristicas_id_caracteristica` ASC) VISIBLE,
  INDEX `fk_Lugares_has_Caracteristicas_Lugares1_idx` (`Lugares_id_lugares` ASC) VISIBLE,
  CONSTRAINT `fk_Lugares_has_Caracteristicas_Caracteristicas1`
    FOREIGN KEY (`Caracteristicas_id_caracteristica`)
    REFERENCES `db_tuso`.`caracteristicas` (`id_caracteristica`),
  CONSTRAINT `fk_Lugares_has_Caracteristicas_Lugares1`
    FOREIGN KEY (`Lugares_id_lugares`)
    REFERENCES `db_tuso`.`lugares` (`id_lugares`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_tuso`.`match`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tuso`.`match` (
  `id_match` INT NOT NULL,
  `Fecha` VARCHAR(45) NOT NULL,
  `Viajes_id_viajes` INT NOT NULL,
  PRIMARY KEY (`id_match`, `Viajes_id_viajes`),
  INDEX `fk_Match_Viajes1_idx` (`Viajes_id_viajes` ASC) VISIBLE,
  CONSTRAINT `fk_Match_Viajes1`
    FOREIGN KEY (`Viajes_id_viajes`)
    REFERENCES `db_tuso`.`viajes` (`id_viajes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_tuso`.`membresias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tuso`.`membresias` (
  `id_membresia` INT NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Fecha_inicio` DATE NOT NULL,
  `Fecha_fin` DATE NOT NULL,
  `Estado` VARCHAR(20) NOT NULL,
  `Usuarios_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_membresia`, `Usuarios_id_usuario`),
  INDEX `fk_Membresias_Usuarios1_idx` (`Usuarios_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Membresias_Usuarios`
    FOREIGN KEY (`Usuarios_id_usuario`)
    REFERENCES `db_tuso`.`usuarios` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_tuso`.`metodos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tuso`.`metodos` (
  `id_metodo` INT NOT NULL,
  `Tipo_pago` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id_metodo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_tuso`.`membresia_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tuso`.`membresia_pago` (
  `Fecha_pago` DATE NOT NULL,
  `Monto` DECIMAL(10,0) NOT NULL,
  `Membresias_id_membresia` INT NOT NULL,
  `Metodos_id_metodo` INT NOT NULL,
  PRIMARY KEY (`Membresias_id_membresia`, `Metodos_id_metodo`),
  INDEX `fk_Membresias_has_Metodos_Metodos1_idx` (`Metodos_id_metodo` ASC) VISIBLE,
  INDEX `fk_Membresias_has_Metodos_Membresias1_idx` (`Membresias_id_membresia` ASC) VISIBLE,
  CONSTRAINT `fk_Membresias_has_Metodos_Membresias1`
    FOREIGN KEY (`Membresias_id_membresia`)
    REFERENCES `db_tuso`.`membresias` (`id_membresia`),
  CONSTRAINT `fk_Membresias_has_Metodos_Metodos1`
    FOREIGN KEY (`Metodos_id_metodo`)
    REFERENCES `db_tuso`.`metodos` (`id_metodo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_tuso`.`notificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tuso`.`notificaciones` (
  `id_notificacion` INT NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Hora_noti` DATETIME NOT NULL,
  `Feed_id_feed` INT NOT NULL,
  `Viajes_id_viajes` INT NOT NULL,
  PRIMARY KEY (`id_notificacion`, `Feed_id_feed`, `Viajes_id_viajes`),
  INDEX `fk_Notificaciones_Feed1_idx` (`Feed_id_feed` ASC) VISIBLE,
  INDEX `fk_Notificaciones_Viajes1_idx` (`Viajes_id_viajes` ASC) VISIBLE,
  CONSTRAINT `fk_Notificaciones_Feed1`
    FOREIGN KEY (`Feed_id_feed`)
    REFERENCES `db_tuso`.`feed` (`id_feed`),
  CONSTRAINT `fk_Notificaciones_Viajes1`
    FOREIGN KEY (`Viajes_id_viajes`)
    REFERENCES `db_tuso`.`viajes` (`id_viajes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_tuso`.`usuario_gustos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tuso`.`usuario_gustos` (
  `Gustos_id_gustos` INT NOT NULL,
  `Usuarios_id_usuario` INT NOT NULL,
  PRIMARY KEY (`Gustos_id_gustos`, `Usuarios_id_usuario`),
  INDEX `fk_Gustos_has_Usuarios_Usuarios1_idx` (`Usuarios_id_usuario` ASC) VISIBLE,
  INDEX `fk_Gustos_has_Usuarios_Gustos1_idx` (`Gustos_id_gustos` ASC) VISIBLE,
  CONSTRAINT `fk_Gustos_has_Usuarios_Gustos1`
    FOREIGN KEY (`Gustos_id_gustos`)
    REFERENCES `db_tuso`.`gustos` (`id_gustos`),
  CONSTRAINT `fk_UsuarioGustos_Gustos`
    FOREIGN KEY (`Gustos_id_gustos`)
    REFERENCES `db_tuso`.`gustos` (`id_gustos`),
  CONSTRAINT `fk_UsuarioGustos_Usuarios`
    FOREIGN KEY (`Usuarios_id_usuario`)
    REFERENCES `db_tuso`.`usuarios` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_tuso`.`viajes_lug`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tuso`.`viajes_lug` (
  `Viajes_id_viajes` INT NOT NULL,
  `Lugares_id_lugares` INT NOT NULL,
  PRIMARY KEY (`Viajes_id_viajes`, `Lugares_id_lugares`),
  INDEX `fk_Viajes_has_Lugares_Lugares1_idx` (`Lugares_id_lugares` ASC) VISIBLE,
  INDEX `fk_Viajes_has_Lugares_Viajes1_idx` (`Viajes_id_viajes` ASC) VISIBLE,
  CONSTRAINT `fk_Viajes_has_Lugares_Lugares1`
    FOREIGN KEY (`Lugares_id_lugares`)
    REFERENCES `db_tuso`.`lugares` (`id_lugares`),
  CONSTRAINT `fk_Viajes_has_Lugares_Viajes1`
    FOREIGN KEY (`Viajes_id_viajes`)
    REFERENCES `db_tuso`.`viajes` (`id_viajes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
